# Generated by Django 3.0.9 on 2020-08-25 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='feautured',
            new_name='featured',
        ),
    ]
